#include "packages.h"

#include "importer.h"

namespace adw::import {

namespace {

// ---- manifests (generated by gen_known_files.py; sizes and md5s only) --------------

const KnownFile kDeluxeKnown[] = {
#include "known_files.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kAd10Known[] = {
#include "known_files_ad10.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kAd32Known[] = {
#include "known_files_ad32.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kTtKnown[] = {
#include "known_files_tt.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kSimpsonsKnown[] = {
#include "known_files_simpsons.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kSwseKnown[] = {
#include "known_files_swse.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kStartrekKnown[] = {
#include "known_files_startrek.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kMarvelKnown[] = {
#include "known_files_marvel.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kSnoopyKnown[] = {
#include "known_files_snoopy.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kLooneyKnown[] = {
#include "known_files_looney.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kScreamsKnown[] = {
#include "known_files_screams.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kDisneyKnown[] = {
#include "known_files_disney.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kFarsideKnown[] = {
#include "known_files_farside.inc"
    {nullptr, 0, nullptr},
};
const KnownFile kDilbertKnown[] = {
#include "known_files_dilbert.inc"
    {nullptr, 0, nullptr},
};

template <size_t N>
std::span<const KnownFile> manifest(const KnownFile (&a)[N]) {
  return std::span<const KnownFile>(a, N - 1);
}

// ---- deluxe ------------------------------------------------------------------------------

// The md5s of two setup pictures, read from the known images: ADE\PAGE1.BMP
// on the Deluxe CD (28198 bytes, 118x226) and INSTALL\SETUP.BMP on the
// Totally Twisted CD (49314 bytes, 387x251).
constexpr char kDeluxePage1Md5[] = "945259b85a1f0a5e0aedfad53561c838";
constexpr char kTtSetupBmpMd5[] = "3e5eee81009de2a2a432cfabf5d7cfea";

const char* const kDeluxeModuleDirs[] = {"AD40", "ENGINE", "CLASSIC"};
const KnownImage kDeluxeImages[] = {
    {kDeluxeIsoMd5, 400234496, "ISO-9660, Mac/PC hybrid CD", "AD_DELUXE"},
};
const Download kDeluxeDownloads[] = {
    {kDeluxeIsoUrl, kDeluxeIsoFileName, 400234496, kDeluxeIsoMd5, "image"},
};
// Without these three engines neither lane can run anything.
const char* const kDeluxeRequired[] = {"AD40/ADXPL510.DLL", "CLASSIC/ADXPL300.DLL", "ENGINE/OLDMOD16.DLL"};
// The folders under ADE\FILES the hosts use (WALLPAPR is desktop wallpaper).
const char* const kDeluxeCopy[] = {"AD40", "CLASSIC", "ENGINE", "AFI"};

// ---- ad10 --------------------------------------------------------------------------------

const char* const kAd10ModuleDirs[] = {"AD10TH", "ENGINE"};
const KnownImage kAd10Images[] = {
    {"a8d088415d391ce0d3199a831e1b2ad6", 150228992, "ISO-9660 + Joliet, Mac/PC hybrid CD", "AD10TH"},
};
// The only exact copy online (darkened once, restored 2024-07-19).
const Download kAd10Downloads[] = {
    {"https://archive.org/download/ad10th/ad10th.iso", L"ad10th.iso", 150228992, "a8d088415d391ce0d3199a831e1b2ad6",
     "image"},
};
const char* const kAd10Required[] = {"AD10TH/ADXPL510.DLL", "AD10TH/ADXPL300.DLL", "AD10TH/ADXPL40.DLL",
                                     "ENGINE/OLDMOD16.DLL", "ENGINE/AD_SND.DLL",   "ENGINE/AFTERDAR.SCR"};
// GAMES (standalone game EXEs) and WALLPAPR are not screen savers.
const char* const kAd10Copy[] = {"AD10TH", "ENGINE", "AFI"};
// Deluxe's FILES has an AD40; the 10th Anniversary's has none.
const char* const kAd10Absent[] = {"AD40"};
// What the original installers did and the modules depend on (SETUP.INF and
// ENGINE\PREVIOUS.INF): ADXPL40 loads TT_SND.DLL from the AD Data Files root
// only, and the Toasters 2k builds open their music by its installed long
// names.
const Fixup kAd10Fixups[] = {
    {"AD10TH/TT_SND.DLL", "AD10TH/MUSIC/TT_SND.DLL"},
    {"AD10TH/MUSIC/Toasters2k.mid", "AD10TH/TOASTER1.MID"},
    {"AD10TH/MUSIC/Flying Toasters.mid", "AD10TH/TOASTERS.MID"},
    {"AD10TH/MUSIC/Baby Toasters.mid", "AD10TH/BABY.MID"},
};
// An earlier build that SETUP.INF never installs; it would otherwise share
// the installed TOASTER2.AD's name.
const NameOverride kAd10Names[] = {
    {"AD10TH/TOAST2K.AD", "Toasters 2k (early build)"},
};

// ---- ad32 --------------------------------------------------------------------------------

const char* const kAd32ModuleDirs[] = {"AD32"};
const KnownImage kAd32Images[] = {
    {"8b8be6977375fbf4d54146b9d505aa1c", 61693952, "ISO-9660, Mac/PC hybrid CD", "ADW320_C"},
};
// Three byte-identical copies, one file name: the curated one first, the
// uncurated upload last.
const Download kAd32Downloads[] = {
    {"https://archive.org/download/after-dark-v3_2/"
     "After%20Dark%203.2%20%281995%29%28Berkeley%20Systems%29%5BMac-PC%5D.iso",
     L"After Dark 3.2 (1995)(Berkeley Systems)[Mac-PC].iso", 61693952, "8b8be6977375fbf4d54146b9d505aa1c", "image"},
    {"https://archive.org/download/berkeley-systems-after-dark-for-windows/berkeley-systems-after-dark-for-windows.iso",
     L"After Dark 3.2 (1995)(Berkeley Systems)[Mac-PC].iso", 61693952, "8b8be6977375fbf4d54146b9d505aa1c", "image"},
    {"https://archive.org/download/3x-2634d-923b-452be-6e-0210afa-3547b-9469-after-dark-3.2-nirvana/ADW320_C.ISO",
     L"After Dark 3.2 (1995)(Berkeley Systems)[Mac-PC].iso", 61693952, "8b8be6977375fbf4d54146b9d505aa1c", "image"},
};
const char* const kAd32Required[] = {"AD32/ADXPL300.DLL", "ENGINE/AD_SND.DLL", "ENGINE/ADTASK.DLL"};
// ScreamSavers' MODMISC.ZIP holds the same ADXPL300.DLL and its AFI.ZIP an
// AD3.AFI too: of every known AD 3.x install, only 3.2's MODMISC.ZIP also
// holds AD30RSDB.DLL (research/win/pkg/more/i2/members.json).
constexpr char kAd32Marker[] = "AD30RSDB.DLL";

// ---- tt ----------------------------------------------------------------------------------

const char* const kTtModuleDirs[] = {"TWISTED"};
const KnownImage kTtImages[] = {
    {"541b9cfd744c377263a4ab1a144bdc12", 39784448, "ISO-9660, Mac/PC hybrid CD", "TTW320CD"},
};
const Download kTtDownloads[] = {
    {"https://archive.org/download/TTW320CD/TTW320CD.ISO", L"TTW320CD.ISO", 39784448, "541b9cfd744c377263a4ab1a144bdc12",
     "image"},
};
const char* const kTtRequired[] = {"TWISTED/ADXPL40.DLL", "TWISTED/TT_SND.DLL", "ENGINE/AD_SND.DLL",
                                   "ENGINE/ADTASK.DLL"};

// ---- simpsons ----------------------------------------------------------------------------

const char* const kSimpsonsModuleDirs[] = {"SIMPSONS"};
const KnownImage kSimpsonsImages[] = {
    {"7674adbda6fc5402d4e7a78af14880cc", 2949120, "FAT12 2.88 MB floppy image (both install disks)", ""},
};
// No image of the floppies exists online (the known image is the owner's own
// merge of both disks, with their notes): two ZIPs of the 28 install files,
// every one md5-identical to the floppies' (the readme CHANGES.TXT, which
// the recipe never reads, is missing). Different bytes, so different names.
const Download kSimpsonsDownloads[] = {
    {"https://archive.org/download/SIMPSONS_WIN/SIMPSONS.zip", L"SIMPSONS.zip", 2752575,
     "90a85bf64c971fe65045f1afc6db0eba", "zip"},
    {"https://archive.org/download/AfterDarkSimpsons/After%20Dark%20-%20The%20Simpsons.zip",
     L"After Dark - The Simpsons.zip", 2752010, "1d6083344b16f09e61acf016eca25026", "zip"},
};
const char* const kSimpsonsRequired[] = {"SIMPSONS/ADXPL310.DLL", "SIMPSONS/SIMP_SND.DLL", "ENGINE/AD_SND.DLL",
                                         "ENGINE/ADTASK.DLL"};
// The 15 module archives, spread over both install floppies.
const char* const kSimpsonsArchives[] = {"BURNS.ZIP",    "CHALKBRD.ZIP", "CLOCKS.ZIP",  "GRAFFITI.ZIP", "GRANDPA.ZIP",
                                         "GRASSKRT.ZIP", "HOMEREAT.ZIP", "HOW2DRAW.ZIP", "INS.ZIP",     "KRUSTY.ZIP",
                                         "MLISA.ZIP",    "PHYSICS.ZIP",  "SFILES.ZIP",  "SNOWBALL.ZIP", "STRIVIA.ZIP"};

// ---- swse --------------------------------------------------------------------------------
//
// Star Wars Screen Entertainment (LucasArts, 1994; by Presage Software) is not
// an After Dark release: its 14 modules are Intermission IMX modules (16-bit
// NE DLLs exporting SAVERINIT/SAVERDRAW, driven by Intermission's IMX reader
// IMIMXPLY.IMQ). The disc is a CD copy of the five install floppies: Presage's
// INSTALL.EXE + INSTALL.DAT, multi-volume ARJ archives and SZDD-compressed
// loose files (research/win/pkg/swse, gitignored).

const char* const kSwseModuleDirs[] = {"SAVER"};
// The CD, and the Redump dump of the same pressing (raw 2352-byte sectors;
// cooked, its first 3529 sectors are that ISO byte for byte).
const KnownImage kSwseImages[] = {
    {"bfa63c1bce15dcbea965dfd7c2ed44e8", 7227392, "ISO-9660 CD of the five install disks", "SWSE"},
    {"ce51614a3484b9269b5ed9e61510e971", 9005808, "the same CD as raw 2352-byte sectors (Redump)", "SWSE"},
};
// The exact ISO; the Redump BIN of it; a flat ZIP of the disc's 40 files,
// each md5-identical to the disc's (verified 2026-09-28:
// research/win/pkg/swse/sources.json). Three files, three names.
const Download kSwseDownloads[] = {
    {"https://archive.org/download/cd_AfterDark_Star_Wars_ScreenSaver_for_Win3.1/AfterDarkStarWars.iso",
     L"AfterDarkStarWars.iso", 7227392, "bfa63c1bce15dcbea965dfd7c2ed44e8", "image"},
    {"https://archive.org/download/swse1/SWSE.bin", L"Star Wars - Screen Entertainment (USA).bin", 9005808,
     "ce51614a3484b9269b5ed9e61510e971", "image"},
    {"https://archive.org/download/swse_20240317/SWSE.zip", L"SWSE.zip", 7013137, "c7a4c5322a784a3e88964c5a7f499226",
     "zip"},
};
// Every install disk: SWSE1.ARJ is disk 1; SWSE2.ARJ and .A01-.A03 are one
// archive over disks 2-5 (INSTALL.DAT [disks]).
const char* const kSwseArchives[] = {"SWSE1.ARJ", "SWSE2.ARJ", "SWSE2.A01", "SWSE2.A02", "SWSE2.A03"};
// What every module loads (INTRMLIB -> ANTSW; SWSE.DLL -> MEMMIDI, SWSFX),
// the IMX reader, and the modules' default settings.
const char* const kSwseRequired[] = {"SAVER/INTRMLIB.DLL", "SAVER/ANTSW.DLL",    "SAVER/SWSE.DLL",
                                     "SAVER/READJPG.DLL",  "SAVER/STRESS.DLL",   "SAVER/SWSFX.DLL",
                                     "SAVER/MEMMIDI.DLL",  "ENGINE/IMIMXPLY.IMQ", "WINDOWS/SWSE.INI"};
// INSTALL.DAT lines 4, 10-13 and 37: STRESS.DLL beside the modules, the
// General MIDI set (CHECK=24) under the names the modules open, directly in
// the module folder as the installer put them in C:\SAVER, and the default
// settings, which it put in C:\WINDOWS.
const LooseFile kSwseLoose[] = {
    {"STRESS.DL_", "SAVER/STRESS.DLL", Codec::szdd},    {"GM_BATTL.MI_", "SAVER/BATTLE.MID", Codec::szdd},
    {"GM_CNTNA.MI_", "SAVER/CANTINA.MID", Codec::szdd}, {"GM_EMPIR.MI_", "SAVER/EMPIRE.MID", Codec::szdd},
    {"GM_TITLE.MI_", "SAVER/SWTHEME.MID", Codec::szdd}, {"SWSE.INI", "WINDOWS/SWSE.INI", Codec::plain},
};
// The names SAVERINIT returns (the modules' SWSE.INI sections); no resource
// holds them.
const NameOverride kSwseNames[] = {
    {"SAVER/BATTLES.IMX", "Space Battles"},    {"SAVER/BIOS.IMX", "Character Biographies"},
    {"SAVER/BLUPRINT.IMX", "Blueprints"},      {"SAVER/CANTINA.IMX", "Cantina"},
    {"SAVER/HYPERSPC.IMX", "Hyperspace"},      {"SAVER/ICLOCK.IMX", "Imperial Clock"},
    {"SAVER/JAWAS.IMX", "Jawas"},              {"SAVER/POSTERS.IMX", "Poster Art"},
    {"SAVER/RCLOCK.IMX", "Rebel Clock"},       {"SAVER/SABRDUEL.IMX", "Lightsaber Duel"},
    {"SAVER/STORYBRD.IMX", "Storyboards"},     {"SAVER/SWTEXT.IMX", "Scrolling Text"},
    {"SAVER/TRENCH.IMX", "Death Star Trench"}, {"SAVER/VADER.IMX", "Darth Vader"},
};

// ---- startrek ----------------------------------------------------------------------------
//
// Star Trek: The Screen Saver ("After Dark, Version 2.0b - The Star Trek
// Edition", Berkeley Systems, 1992): 16 After Dark 2.0 modules (16-bit NE DLLs
// exporting MODULE, the Classic lane) on two 1.44 MB floppies installed by
// Microsoft Setup 2.0, nearly every file KWAJ-compressed (kwaj.h). The recipe
// is ST_NSTLL.INF and AD_NSTLL.MST baked into a table: SETUP.LST is read only
// to identify the release (research/win/pkg/startrek, gitignored).

// The modules' own folder: the installer's C:\AFTERDRK, which the 16-bit lane
// mounts there (the modules find ST_RES\ and SOUNDS\ below AD_PREFS.INI's
// [After Dark] Path).
const char* const kStartrekModuleDirs[] = {"AFTERDRK"};
// The Internet Archive's two images (item afterdark-20b_startrek, also what
// the user's ZIP holds), and the same disks as a Windows 9x copy wrote to them
// (item startrektosscreensaver1992win: the boot sector's OEM name and
// root-directory access dates differ; every file is the same byte for byte).
// A release on two disks: only a set of both is the release.
const KnownImage kStartrekImages[] = {
    {"28e33608b8d3bafa28585472c4a7a9ac", 1474560, "FAT12 1.44 MB floppy image, install disk 1 of 2", "", 1},
    {"c630da5f6839303b599947f56fdd7c25", 1474560, "FAT12 1.44 MB floppy image, install disk 2 of 2", "", 2},
    {"6ee71b45e32b07001d46ab8c80af589d", 1474560,
     "FAT12 1.44 MB floppy image, install disk 1 of 2 (a copy Windows 9x wrote to)", "", 1},
    {"af9d29a7ddea2c03618899c1c5733c67", 1474560,
     "FAT12 1.44 MB floppy image, install disk 2 of 2 (a copy Windows 9x wrote to)", "", 2},
};
// Both copies are images of both disks (verified 2026-09-29:
// research/win/pkg/startrek/importer/sources.json); each part is checked
// against its published size and md5. Other bytes, other names. (The user's
// own ZIP is the Internet Archive's on-the-fly ZIP of the first item, whose
// md5 changes with every download: it is identified by its images' md5s.)
const DownloadPart kStartrekDisk2[] = {
    {"https://archive.org/download/afterdark-20b_startrek/afterdark-20b_startrek_disk2.img",
     L"afterdark-20b_startrek_disk2.img", 1474560, "c630da5f6839303b599947f56fdd7c25"},
};
const DownloadPart kStartrekDisk2Win9x[] = {
    {"https://archive.org/download/startrektosscreensaver1992win/startrek2.img", L"startrek2.img", 1474560,
     "af9d29a7ddea2c03618899c1c5733c67"},
};
const Download kStartrekDownloads[] = {
    {"https://archive.org/download/afterdark-20b_startrek/afterdark-20b_startrek_disk1.img",
     L"afterdark-20b_startrek_disk1.img", 1474560, "28e33608b8d3bafa28585472c4a7a9ac", "image", kStartrekDisk2},
    {"https://archive.org/download/startrektosscreensaver1992win/startrek1.img", L"startrek1.img", 1474560,
     "6ee71b45e32b07001d46ab8c80af589d", "image", kStartrekDisk2Win9x},
};
// What the modules cannot run without: their framework (AD_MOD, AD_RSRC), the
// art and sound databases AD_MOD opens from <Path>ST_RES\, and the sound
// library the native bridge loads.
const char* const kStartrekRequired[] = {
    "AFTERDRK/AD_MOD.DLL",          "AFTERDRK/AD_RSRC.DLL",       "AFTERDRK/ST_RES/ST_RESDB.DLL",
    "AFTERDRK/ST_RES/ST_MASKS.DLL", "AFTERDRK/ST_RES/ST_VGA.DLL", "AFTERDRK/ST_RES/ST_SVGA.DLL",
    "AFTERDRK/ST_RES/ST_SND.DLL",   "ENGINE/AD_SND.DLL"};
// Every install disk: the tag files of ST_NSTLL.INF [Source Media
// Descriptions] (disk 1's is the fingerprint's, beside SETUP.LST).
const char* const kStartrekDiskTags[] = {"MISSION.AD_", "ST_SND.DL_"};
// ST_NSTLL.INF and AD_NSTLL.MST, flattened: what the modules use, nothing
// edited. The modules and their DLLs in the module folder, as installed in
// C:\AFTERDRK (the installer put AD_MOD and AD_RSRC in C:\WINDOWS; the
// modules import them, so they sit beside them, invariant I2); the
// multimedia sound driver AD_SND loads from there ([Sound] SoundDriver);
// ST_RES\ and SOUNDS\ below it (Sounder refuses to load without a .WAV);
// AD_SND 1.0 and the pristine AD.EXE in ENGINE (the host replaces AD.EXE, which
// is kept for reference as INTERMIS.EXE is; nothing loads it). Never
// installed: the disk's AD_PREFS.INI (its SoundDriver=AD_MPT.DRV would win
// over the lane's seed and hang the emulator), the PC-speaker path
// (AD_MPT.DRV, SPALETTE.DLL, AD_LIB.DLL), AD_SB.DRV (it refuses Windows 3.1
// and later), the network password DLLs and utility, AD.386, AD_WRAP.COM,
// AFTERDRK.NSS, ADINIT.EXE, AD.HLP, AD_MESG.ADS (the data of a Messages module
// this release does not ship) and every setup file.
const LooseFile kStartrekLoose[] = {
    {"BRAINCEL.AD_", "AFTERDRK/BRAINCEL.AD", Codec::kwaj},
    {"COMMS.AD_", "AFTERDRK/COMMS.AD", Codec::kwaj},
    {"FINAL.AD_", "AFTERDRK/FINAL.AD", Codec::kwaj},
    {"FRONTIER.AD_", "AFTERDRK/FRONTIER.AD", Codec::kwaj},
    {"HORTA.AD_", "AFTERDRK/HORTA.AD", Codec::kwaj},
    {"IONSTORM.AD_", "AFTERDRK/IONSTORM.AD", Codec::kwaj},
    {"MISSION.AD_", "AFTERDRK/MISSION.AD", Codec::kwaj},
    {"PANELS.AD_", "AFTERDRK/PANELS.AD", Codec::kwaj},
    {"PLANETS.AD_", "AFTERDRK/PLANETS.AD", Codec::kwaj},
    {"SCOTTYS.AD_", "AFTERDRK/SCOTTYS.AD", Codec::kwaj},
    {"SICKBAY.AD_", "AFTERDRK/SICKBAY.AD", Codec::kwaj},
    {"SOUNDER.AD_", "AFTERDRK/SOUNDER.AD", Codec::kwaj},
    {"SPACE.AD_", "AFTERDRK/SPACE.AD", Codec::kwaj},
    {"SPOCK.AD_", "AFTERDRK/SPOCK.AD", Codec::kwaj},
    {"THOLIAN.AD_", "AFTERDRK/THOLIAN.AD", Codec::kwaj},
    {"TRIBBLE.AD_", "AFTERDRK/TRIBBLE.AD", Codec::kwaj},
    {"AD_MOD.DL_", "AFTERDRK/AD_MOD.DLL", Codec::kwaj},
    {"AD_RSRC.DL_", "AFTERDRK/AD_RSRC.DLL", Codec::kwaj},
    {"AD_MME.DR_", "AFTERDRK/AD_MME.DRV", Codec::kwaj},
    {"ST_RESDB.DL_", "AFTERDRK/ST_RES/ST_RESDB.DLL", Codec::kwaj},
    {"ST_MASKS.DL_", "AFTERDRK/ST_RES/ST_MASKS.DLL", Codec::kwaj},
    {"ST_VGA.DL_", "AFTERDRK/ST_RES/ST_VGA.DLL", Codec::kwaj},
    {"ST_SVGA.DL_", "AFTERDRK/ST_RES/ST_SVGA.DLL", Codec::kwaj},
    {"ST_SND.DL_", "AFTERDRK/ST_RES/ST_SND.DLL", Codec::kwaj},
    {"JIM.WA_", "AFTERDRK/SOUNDS/JIM.WAV", Codec::kwaj},
    {"AD_SND.DL_", "ENGINE/AD_SND.DLL", Codec::kwaj},
    {"AD.EX_", "ENGINE/AD.EXE", Codec::kwaj},
};
// PLANETS.AD's name resource says " PlanetaryAtlas"; its About heading and
// Berkeley's own later PREVIOUS.INF (After Dark 4.0 Deluxe) say "Planetary
// Atlas".
const NameOverride kStartrekNames[] = {
    {"AFTERDRK/PLANETS.AD", "Planetary Atlas"},
};

// ---- marvel ------------------------------------------------------------------------------
//
// Marvel Comics Screen Posters (Berkeley Systems, December 1993, under
// licence from Marvel): one After Dark 2.0 module, MARVEL.AD, a slide show of
// 36 posters in Iterated Systems' fractal format, which its DECO.DLL decodes,
// on After Dark 2.0d. Two floppies installed by InstallShield 2.00: every
// file in compressed libraries (isz.h), the images in one split over both
// disks, IMAGES.1 + IMAGES.2 (research/win/pkg/marvel, gitignored). No image
// of the floppies exists online: its known copies are two ZIPs of their
// files on the Internet Archive, one of them the user's copy byte for byte.

// The module's folder: the installer's C:\AFTERDRK, which the 16-bit lane
// mounts there (the module opens its images from <[After Dark] Path>\MRVLIMAG).
const char* const kMarvelModuleDirs[] = {"AFTERDRK"};
// The flat ZIP of the twelve install files (item afterdarkmarvelscreenposters,
// without the previous owners' notes), and the ZIP of both disks in Disk1 and
// Disk2 folders (item after-dark-collection): each file of the one is the
// other's, byte for byte.
const KnownImage kMarvelImages[] = {
    {"4c608dbbeb34108b30ede88304912c94", 2039771,
     "ZIP of the install files of both floppies (the Internet Archive's afterdarkmarvelscreenposters copy)", ""},
    {"6981b36abb04779a076466fabad3721c", 2046286,
     "ZIP of both install floppies' files, in Disk1 and Disk2 folders (the Internet Archive's after-dark-collection "
     "copy)",
     ""},
};
// The flat ZIP first (the item that also holds the box photo); other bytes,
// other names. Neither item's serial number file is ever fetched.
const Download kMarvelDownloads[] = {
    {"https://archive.org/download/afterdarkmarvelscreenposters/After%20Dark%20-%20Marvel%20Screen%20Posters.zip",
     L"After Dark - Marvel Screen Posters.zip", 2039771, "4c608dbbeb34108b30ede88304912c94", "zip"},
    {"https://archive.org/download/after-dark-collection/After%20Dark%20-%20Marvel%20Comics.zip",
     L"After Dark - Marvel Comics.zip", 2046286, "6981b36abb04779a076466fabad3721c", "zip"},
};
// What the module cannot run without: the decoder it imports, the image
// catalog it refuses to start without, and the sound library the native
// bridge loads.
const char* const kMarvelRequired[] = {"AFTERDRK/DECO.DLL", "AFTERDRK/MRVLIMAG/MRVLIMAG.ADC", "ENGINE/AD_SND.DLL"};
// Every library the recipe reads, every install disk's: images.lib (IMAGES.1
// on disk 1, beside SETUP.PKG; IMAGES.2 on disk 2), modules.lib, engine.lib
// and win.lib (disk 2).
const char* const kMarvelLibraries[] = {"IMAGES.1", "IMAGES.2", "MODULES.LIB", "ENGINE.LIB", "WIN.LIB"};
// INSTALL.INS's full install, flattened: the module and its decoder in the
// module folder (C:\AFTERDRK), every image and the image catalog in MRVLIMAG\
// below it (C:\AFTERDRK\MRVLIMAG), AD_SND 1.0 (which the installer put in
// C:\WINDOWS) and the pristine AD.EXE in ENGINE (the host replaces AD.EXE,
// which is kept for reference as Star Trek's is; nothing loads it). Never
// installed: the rest of engine.lib (the PC-speaker and Sound Blaster
// drivers, AD_MME.DRV, AD_LIB.DLL, ADINIT.EXE, the manual MRVL.WRI and the
// four readme texts), the rest of win.lib (the disk's AD_PREFS.INI, whose
// PC-speaker driver would hang the emulator, AD.HLP, AD_WRAP.COM,
// SPALETTE.DLL), winsys.lib (AD.386) and the installer's own ~INS0762.LIB.
const LibraryMember kMarvelTable[] = {
    {"MODULES.LIB", "MARVEL.AD", "AFTERDRK/MARVEL.AD"},
    {"MODULES.LIB", "DECO.DLL", "AFTERDRK/DECO.DLL"},
    {"ENGINE.LIB", "AD.EXE", "ENGINE/AD.EXE"},
    {"WIN.LIB", "AD_SND.DLL", "ENGINE/AD_SND.DLL"},
    {"IMAGES.1", "AV2.FTT", "AFTERDRK/MRVLIMAG/AV2.FTT"},
    {"IMAGES.1", "AVENGE#4.FIF", "AFTERDRK/MRVLIMAG/AVENGE#4.FIF"},
    {"IMAGES.1", "CABLE.FIF", "AFTERDRK/MRVLIMAG/CABLE.FIF"},
    {"IMAGES.1", "CABLE.FTT", "AFTERDRK/MRVLIMAG/CABLE.FTT"},
    {"IMAGES.1", "CAPT.FIF", "AFTERDRK/MRVLIMAG/CAPT.FIF"},
    {"IMAGES.1", "CAPT.FTT", "AFTERDRK/MRVLIMAG/CAPT.FTT"},
    {"IMAGES.1", "CAPTAINA.FIF", "AFTERDRK/MRVLIMAG/CAPTAINA.FIF"},
    {"IMAGES.1", "CAPTAINA.FTT", "AFTERDRK/MRVLIMAG/CAPTAINA.FTT"},
    {"IMAGES.1", "CAPTAINW.FIF", "AFTERDRK/MRVLIMAG/CAPTAINW.FIF"},
    {"IMAGES.1", "CLOBBERI.FIF", "AFTERDRK/MRVLIMAG/CLOBBERI.FIF"},
    {"IMAGES.1", "COVER.FTT", "AFTERDRK/MRVLIMAG/COVER.FTT"},
    {"IMAGES.1", "DAREDEVI.FIF", "AFTERDRK/MRVLIMAG/DAREDEVI.FIF"},
    {"IMAGES.1", "DAREDEVI.FTT", "AFTERDRK/MRVLIMAG/DAREDEVI.FTT"},
    {"IMAGES.1", "FAN4#1.FIF", "AFTERDRK/MRVLIMAG/FAN4#1.FIF"},
    {"IMAGES.1", "FAN4#1.FTT", "AFTERDRK/MRVLIMAG/FAN4#1.FTT"},
    {"IMAGES.1", "FANT0A.FTT", "AFTERDRK/MRVLIMAG/FANT0A.FTT"},
    {"IMAGES.1", "FANT0WFB.FIF", "AFTERDRK/MRVLIMAG/FANT0WFB.FIF"},
    {"IMAGES.1", "FANTAST0.FTT", "AFTERDRK/MRVLIMAG/FANTAST0.FTT"},
    {"IMAGES.1", "GAMBWOLV.FIF", "AFTERDRK/MRVLIMAG/GAMBWOLV.FIF"},
    {"IMAGES.1", "GHOST.FTT", "AFTERDRK/MRVLIMAG/GHOST.FTT"},
    {"IMAGES.1", "GHOSTID.FIF", "AFTERDRK/MRVLIMAG/GHOSTID.FIF"},
    {"IMAGES.1", "HULK#1.FIF", "AFTERDRK/MRVLIMAG/HULK#1.FIF"},
    {"IMAGES.1", "HULK#1.FTT", "AFTERDRK/MRVLIMAG/HULK#1.FTT"},
    {"IMAGES.1", "HULKFACE.FIF", "AFTERDRK/MRVLIMAG/HULKFACE.FIF"},
    {"IMAGES.1", "HUMANTOR.FIF", "AFTERDRK/MRVLIMAG/HUMANTOR.FIF"},
    {"IMAGES.1", "IRONMAN.FIF", "AFTERDRK/MRVLIMAG/IRONMAN.FIF"},
    {"IMAGES.1", "IRONMAN2.FTT", "AFTERDRK/MRVLIMAG/IRONMAN2.FTT"},
    {"IMAGES.1", "MRVLIMAG.ADC", "AFTERDRK/MRVLIMAG/MRVLIMAG.ADC"},
    {"IMAGES.1", "PUNISHER.FIF", "AFTERDRK/MRVLIMAG/PUNISHER.FIF"},
    {"IMAGES.1", "PUNISHER.FTT", "AFTERDRK/MRVLIMAG/PUNISHER.FTT"},
    {"IMAGES.1", "PUNISHLA.FIF", "AFTERDRK/MRVLIMAG/PUNISHLA.FIF"},
    {"IMAGES.1", "PUNISHLO.FTT", "AFTERDRK/MRVLIMAG/PUNISHLO.FTT"},
    {"IMAGES.1", "SABRETOO.FIF", "AFTERDRK/MRVLIMAG/SABRETOO.FIF"},
    {"IMAGES.1", "SHE-HULK.FIF", "AFTERDRK/MRVLIMAG/SHE-HULK.FIF"},
    {"IMAGES.1", "SHE-HULK.FTT", "AFTERDRK/MRVLIMAG/SHE-HULK.FTT"},
    {"IMAGES.1", "SILVERSA.FIF", "AFTERDRK/MRVLIMAG/SILVERSA.FIF"},
    {"IMAGES.1", "SILVERSU.FIF", "AFTERDRK/MRVLIMAG/SILVERSU.FIF"},
    {"IMAGES.1", "SILVERSU.FTT", "AFTERDRK/MRVLIMAG/SILVERSU.FTT"},
    {"IMAGES.1", "SILVRSU2.FIF", "AFTERDRK/MRVLIMAG/SILVRSU2.FIF"},
    {"IMAGES.1", "SILVRSU2.FTT", "AFTERDRK/MRVLIMAG/SILVRSU2.FTT"},
    {"IMAGES.1", "SPIDATTA.FIF", "AFTERDRK/MRVLIMAG/SPIDATTA.FIF"},
    {"IMAGES.1", "SPIDERCO.FIF", "AFTERDRK/MRVLIMAG/SPIDERCO.FIF"},
    {"IMAGES.1", "SPIDEY#1.FTT", "AFTERDRK/MRVLIMAG/SPIDEY#1.FTT"},
    {"IMAGES.1", "SPIDEY1W.FIF", "AFTERDRK/MRVLIMAG/SPIDEY1W.FIF"},
    {"IMAGES.1", "SPIDEYAT.FTT", "AFTERDRK/MRVLIMAG/SPIDEYAT.FTT"},
    {"IMAGES.1", "SPIDEYID.FIF", "AFTERDRK/MRVLIMAG/SPIDEYID.FIF"},
    {"IMAGES.1", "SPIDEYSW.FTT", "AFTERDRK/MRVLIMAG/SPIDEYSW.FTT"},
    {"IMAGES.1", "SPIDEYVE.FIF", "AFTERDRK/MRVLIMAG/SPIDEYVE.FIF"},
    {"IMAGES.1", "SPIDEYVE.FTT", "AFTERDRK/MRVLIMAG/SPIDEYVE.FTT"},
    {"IMAGES.1", "SPIDSWIN.FIF", "AFTERDRK/MRVLIMAG/SPIDSWIN.FIF"},
    {"IMAGES.1", "THORA.FIF", "AFTERDRK/MRVLIMAG/THORA.FIF"},
    {"IMAGES.1", "THORA.FTT", "AFTERDRK/MRVLIMAG/THORA.FTT"},
    {"IMAGES.1", "WOLNSAB.FIF", "AFTERDRK/MRVLIMAG/WOLNSAB.FIF"},
    {"IMAGES.1", "WOLVIE.FIF", "AFTERDRK/MRVLIMAG/WOLVIE.FIF"},
    {"IMAGES.1", "WOLVRIP.FIF", "AFTERDRK/MRVLIMAG/WOLVRIP.FIF"},
    {"IMAGES.1", "WOMENFX.FIF", "AFTERDRK/MRVLIMAG/WOMENFX.FIF"},
    {"IMAGES.1", "WOMENFX.FTT", "AFTERDRK/MRVLIMAG/WOMENFX.FTT"},
    {"IMAGES.1", "X-MENVS.FIF", "AFTERDRK/MRVLIMAG/X-MENVS.FIF"},
    {"IMAGES.1", "XMEN2099.FIF", "AFTERDRK/MRVLIMAG/XMEN2099.FIF"},
    {"IMAGES.1", "XMENATTA.FIF", "AFTERDRK/MRVLIMAG/XMENATTA.FIF"},
};

// ---- snoopy ------------------------------------------------------------------------------
//
// Snoopy's Screen Savers 1.0 (Image Smith, 1994; the Peanuts characters under
// licence from United Feature Syndicate): eight After Dark modules for an
// After Dark 2.0 or 3.0 already installed, with no engine, no AD_SND and no
// palettes of their own. Two floppies installed by InstallShield 2.00: the
// modules in one compressed library split over both disks, AD_MODS.1 +
// AD_MODS.2 (research/win/pkg/snoopy, gitignored). No image of the floppies
// exists online: its known copy is the Internet Archive's ZIP of their files,
// the user's copy byte for byte.

// The modules' folder: the directory of the After Dark they were installed
// into (the installer's default C:\AFTERDRK).
const char* const kSnoopyModuleDirs[] = {"AFTERDRK"};
const KnownImage kSnoopyImages[] = {
    {"a712447e1c957767bdbca884cead02dc", 1993700,
     "ZIP of both install floppies' files, in Disk1 and Disk2 folders (the Internet Archive's after-dark-collection "
     "copy)",
     ""},
};
const Download kSnoopyDownloads[] = {
    {"https://archive.org/download/after-dark-collection/After%20Dark%20-%20Snoopy.zip", L"After Dark - Snoopy.zip",
     1993700, "a712447e1c957767bdbca884cead02dc", "zip"},
};
// Both volumes of the library, one per install disk (AD_MODS.1 beside
// SETUP.PKG on disk 1).
const char* const kSnoopyLibraries[] = {"AD_MODS.1", "AD_MODS.2"};
// SETUP.INS copies every member of AD_MODS.z into the After Dark directory,
// and nothing else.
const LibraryMember kSnoopyTable[] = {
    {"AD_MODS.1", "IS_COLAG.AD", "AFTERDRK/IS_COLAG.AD"}, {"AD_MODS.1", "IS_DANCE.AD", "AFTERDRK/IS_DANCE.AD"},
    {"AD_MODS.1", "IS_FACES.AD", "AFTERDRK/IS_FACES.AD"}, {"AD_MODS.1", "IS_FLY.AD", "AFTERDRK/IS_FLY.AD"},
    {"AD_MODS.1", "IS_LINUS.AD", "AFTERDRK/IS_LINUS.AD"}, {"AD_MODS.1", "IS_LITRY.AD", "AFTERDRK/IS_LITRY.AD"},
    {"AD_MODS.1", "IS_SPTLT.AD", "AFTERDRK/IS_SPTLT.AD"}, {"AD_MODS.1", "IS_THRPY.AD", "AFTERDRK/IS_THRPY.AD"},
};

// ---- looney ------------------------------------------------------------------------------
//
// The Looney Tunes Screen Saver (Berkeley Systems, April 1995, under licence
// from Warner Bros.): 12 AD 3.x Classic modules on their own engine,
// ADXPL41.DLL, with a sound database, LT_SOUND.DLL, and the After Dark 3.0
// host of early 1995; the same InstallShield install of encrypted ZIPs as
// 3.2's (research/win/pkg/looney, gitignored). Build A, the April release:
// the Internet Archive's ZIP of its install files is the user's copy byte for
// byte, and the LOONEY_T CD holds the same 30 files. (Build B, the August CD
// LTW320CD, has the same modules on 3.2's engine files: identified as this
// package, it fails verification, and --no-verify imports it.)

const char* const kLooneyModuleDirs[] = {"LNYTUNES"};
// The ZIP, and the CD of the same files. The CD's only copy online is named
// (in its URL too) after what another item publishes as the product's serial
// number: it is known by md5, size and volume id only, and never downloaded.
const KnownImage kLooneyImages[] = {
    {"642b358a4854c481fe99984b8452ceb5", 2900525,
     "ZIP of the install files of both floppies (the Internet Archive's after-dark-collection copy)", ""},
    {"6ad72e19b2cf6fcb9e67427f8e600449", 6625280, "ISO-9660 CD of the install files of both floppies", "LOONEY_T"},
};
const Download kLooneyDownloads[] = {
    {"https://archive.org/download/after-dark-collection/After%20Dark%20-%20Looney%20Tunes.zip",
     L"After Dark - Looney Tunes.zip", 2900525, "642b358a4854c481fe99984b8452ceb5", "zip"},
};
const char* const kLooneyRequired[] = {"LNYTUNES/ADXPL41.DLL", "LNYTUNES/LT_SOUND.DLL", "ENGINE/AD_SND.DLL",
                                       "ENGINE/ADTASK.DLL"};
// The 12 module archives and MUSIC.ZIP, over both install floppies.
const char* const kLooneyArchives[] = {"ACMESHOP.ZIP", "CART101.ZIP", "CONDUCKT.ZIP", "FROG.ZIP",  "LTMESSGS.ZIP",
                                       "MARVIN.ZIP",   "PEPE.ZIP",    "PUTTYTAT.ZIP", "RABBITRN.ZIP", "SAM.ZIP",
                                       "TAZ.ZIP",      "WOCKETS.ZIP", "MUSIC.ZIP"};

// ---- screams -----------------------------------------------------------------------------
//
// ScreamSavers ("Stephen Blickenstaff's ScreamSavers", Binary Software, 1995):
// 15 AD 3.x Classic modules on After Dark 3.0.6, which Binary Software
// licensed from Berkeley, on three floppies with the same InstallShield
// install as 3.2's (research/win/pkg/scream, gitignored). The modules import
// only AD_SND; MODMISC.ZIP holds 3.2's ADXPL300.DLL, installed as the
// installer did though nothing loads it. The only copy online is the
// Internet Archive's ZIP of the three disks' files in DISK1-DISK3 folders,
// the user's copy byte for byte.

const char* const kScreamsModuleDirs[] = {"SCREAMS"};
const KnownImage kScreamsImages[] = {
    {"37a47b25dd35b214f94f57b6a0c2bd02", 3453163,
     "ZIP of the three install floppies' files, in DISK1-DISK3 folders (the Internet Archive's after-dark-collection "
     "copy)",
     ""},
};
const Download kScreamsDownloads[] = {
    {"https://archive.org/download/after-dark-collection/After%20Dark%20-%20Scream%20Savers.zip",
     L"After Dark - Scream Savers.zip", 3453163, "37a47b25dd35b214f94f57b6a0c2bd02", "zip"},
};
const char* const kScreamsRequired[] = {"ENGINE/AD_SND.DLL", "ENGINE/ADTASK.DLL"};
// The 15 module archives, over the three install floppies.
const char* const kScreamsArchives[] = {"AMPHIBO.ZIP", "BELCHO.ZIP",   "BUGZAP.ZIP",   "GRISTLE.ZIP",  "HEADBUTT.ZIP",
                                        "INFECTO.ZIP", "LOCKJAW.ZIP",  "MALIGNO.ZIP",  "MELTICOR.ZIP", "MOONBITE.ZIP",
                                        "PUPPY.ZIP",   "SNAPPY.ZIP",   "SPEWER.ZIP",   "STICKY.ZIP",   "TWISTER.ZIP"};

// ---- disney ------------------------------------------------------------------------------
//
// The Disney Collection Screen Saver (Berkeley Systems, 1995): the 1993
// Disney modules re-released on the After Dark 3.2 engine, 16 Classic modules
// on the After Dark 2.0-era library ADXPL100.DLL with a sound library,
// DIS_SND.DLL, in the same InstallShield install as 3.2's
// (research/win/pkg/disney, gitignored). No image of its disks exists online:
// its known copy is the Internet Archive's ZIP of the three disks' files, the
// user's copy byte for byte. (The 1993 edition, on After Dark 2.0 and
// InstallShield libraries, is another release.)

const char* const kDisneyModuleDirs[] = {"DISNEY"};
const KnownImage kDisneyImages[] = {
    {"2f38df15494728b5bc20d26c36ba84c7", 3560012,
     "ZIP of the install files of the three floppies (the Internet Archive's after-dark-collection copy)", ""},
};
const Download kDisneyDownloads[] = {
    {"https://archive.org/download/after-dark-collection/After%20Dark%20-%20Disney%20Collection.zip",
     L"After Dark - Disney Collection.zip", 3560012, "2f38df15494728b5bc20d26c36ba84c7", "zip"},
};
// The library the modules import and the one it loads by name from the AD
// Data Files root (AD_PREFS.INI's [After Dark] Path).
const char* const kDisneyRequired[] = {"DISNEY/ADXPL100.DLL", "DISNEY/DIS_SND.DLL", "ENGINE/AD_SND.DLL",
                                       "ENGINE/ADTASK.DLL"};
// The 16 module archives, over the three install floppies.
const char* const kDisneyArchives[] = {"BEAUTY.ZIP",  "CHECAT.ZIP",  "DALM.ZIP",    "DONDUK.ZIP",
                                       "DSCLOCKS.ZIP", "FALLING.ZIP", "FIREWRK.ZIP", "GOOFY.ZIP",
                                       "HAUNTED.ZIP", "HOOK.ZIP",    "INKWELL.ZIP", "JUNGLE.ZIP",
                                       "MERMAID.ZIP", "PINOCCHI.ZIP", "SCROOGE.ZIP", "SORCERER.ZIP"};
// The 1993 build of BEAUTY.AD, which only the installer's last function
// names (beside "CopyFile failed for"): the release installs BEAUTY.ZIP's
// 1995 build, the one Berkeley's checksum list (CHEKSUMS.NEW) names. Two
// archives holding one name would otherwise be two files for one path.
const char* const kDisneyNeverOpened[] = {"BEAUTYOL.ZIP"};
// Five names lost their space to the name resource's 16 bytes; each
// module's own description (and Berkeley's product page) spells it out.
const NameOverride kDisneyNames[] = {
    {"DISNEY/DALM.AD", "101 Dalmatians"}, {"DISNEY/DSCLOCKS.AD", "Disney Clocks"},
    {"DISNEY/FALLING.AD", "Falling Flower"}, {"DISNEY/FIREWRK.AD", "Magic Kingdom"},
    {"DISNEY/MERMAID.AD", "Little Mermaid"},
};

// ---- farside -----------------------------------------------------------------------------
//
// The Far Side Screen Saver Collection (Delrina, June 1994; Gary Larson's
// cartoons under licence) on Intermission 4.0: 14 modules of Intermission's
// two other forms — 12 ASA animations (data files starting "AniN", "AniM" for
// EGGFIGHT, that Intermission's ASA reader IMASAPLY.IMQ plays) and two IMQ
// modules (PTERY, NERDCLOK: 16-bit NE DLLs exporting SAVERMAIN, each its own
// reader). Five 1.44 MB floppies installed by Delrina's own Intermission
// Installer (SETUP.EXE, IMINST2.EXE): every file loose, most SZDD-compressed
// under their installed names, everything put in C:\SAVER
// (research/win/pkg/farside, gitignored). Its engine files INTRMLIB, ANTSW,
// MEMMIDI and IMIMXPLY are Star Wars Screen Entertainment's byte for byte.

const char* const kFarsideModuleDirs[] = {"SAVER"};
// The only intact copy online: a 1994 BBS repack of the five floppies, one
// ZIP per disk (PNX-FSC1..5.ZIP, the disks' files with their dates and the
// group's notes beside them, which nothing ever opens), inside the Internet
// Archive's prog47_55 item. The item named for the release
// (the-far-side-screen-saver-collection-1-of-5) holds floppy images of which
// only disk 5's is exact (disk 1's is sector-shifted, disk 3's short, disks 2
// and 4 have bad sectors in AERIAL.ASA and FISHBOWL.ASA): never listed. A
// release on five disks: only a set of all five is the release.
const KnownImage kFarsideImages[] = {
    {"bfbe487438204b3573e913a774ee964d", 977668,
     "ZIP of install disk 1's files (a 1994 BBS copy of the five floppies)", "", 1},
    {"364307265d011ba3e31d383bc178d56d", 1210777,
     "ZIP of install disk 2's files (a 1994 BBS copy of the five floppies)", "", 2},
    {"5ac67d84f9a5262f40c92e9f143fdb03", 1202730,
     "ZIP of install disk 3's files (a 1994 BBS copy of the five floppies)", "", 3},
    {"7902b2a2a89eb7ed391e179a27958061", 1106810,
     "ZIP of install disk 4's files (a 1994 BBS copy of the five floppies)", "", 4},
    {"58351b2eedd8f6ef5ec51fa00c4d8d17", 1248997,
     "ZIP of install disk 5's files (a 1994 BBS copy of the five floppies)", "", 5},
};
// The five ZIPs, each fetched from inside the item's ZIP (the Internet
// Archive serves a member of a stored ZIP by its path; it publishes no md5
// for one: these are the members' own, measured 2026-09-30:
// research/win/pkg/farside).
const DownloadPart kFarsideDisks2to5[] = {
    {"https://archive.org/download/prog47_55/prog47_55.zip/prog47_55%2FPROG_52%2FPNX-FSC2.ZIP", L"PNX-FSC2.ZIP",
     1210777, "364307265d011ba3e31d383bc178d56d"},
    {"https://archive.org/download/prog47_55/prog47_55.zip/prog47_55%2FPROG_52%2FPNX-FSC3.ZIP", L"PNX-FSC3.ZIP",
     1202730, "5ac67d84f9a5262f40c92e9f143fdb03"},
    {"https://archive.org/download/prog47_55/prog47_55.zip/prog47_55%2FPROG_52%2FPNX-FSC4.ZIP", L"PNX-FSC4.ZIP",
     1106810, "7902b2a2a89eb7ed391e179a27958061"},
    {"https://archive.org/download/prog47_55/prog47_55.zip/prog47_55%2FPROG_52%2FPNX-FSC5.ZIP", L"PNX-FSC5.ZIP",
     1248997, "58351b2eedd8f6ef5ec51fa00c4d8d17"},
};
const Download kFarsideDownloads[] = {
    {"https://archive.org/download/prog47_55/prog47_55.zip/prog47_55%2FPROG_52%2FPNX-FSC1.ZIP", L"PNX-FSC1.ZIP",
     977668, "bfbe487438204b3573e913a774ee964d", "zip", kFarsideDisks2to5},
};
// What every module loads (INTRMLIB -> ANTSW; PTERY also DIBDLL; the ASA
// reader MEMMIDI, by name) and the ASA reader.
const char* const kFarsideRequired[] = {"SAVER/INTRMLIB.DLL", "SAVER/ANTSW.DLL", "SAVER/DIBDLL.DLL",
                                        "SAVER/MEMMIDI.DLL", "ENGINE/IMASAPLY.IMQ"};
// Every install disk's tag file (disk 1's, beside the installer and
// PTERY.IMQ, is the fingerprint's).
const char* const kFarsideDiskTags[] = {"DISK1", "DISK2", "DISK3", "DISK4", "DISK5"};
// IMINST2's install, flattened: the modules and the DLLs they load in the
// module folder (its C:\SAVER), the ASA reader and Intermission itself
// (replaced by the host, kept for reference as Star Wars Screen
// Entertainment's is) in ENGINE. Never installed: AD_SND.DLL (on any search
// path it breaks the After Dark bridge) and the other readers, IWLIB.DLL,
// NETPASS.EXE, SSINTERM.SCR, the VxD, the control panel, the sound drivers,
// the DOS and setup programs, the help file and the texts.
const LooseFile kFarsideLoose[] = {
    {"AERIAL.ASA", "SAVER/AERIAL.ASA", Codec::szdd},     {"AMOEBA.ASA", "SAVER/AMOEBA.ASA", Codec::szdd},
    {"BIRDS.ASA", "SAVER/BIRDS.ASA", Codec::szdd},       {"BISON.ASA", "SAVER/BISON.ASA", Codec::szdd},
    {"EGGFIGHT.ASA", "SAVER/EGGFIGHT.ASA", Codec::szdd}, {"FISH.ASA", "SAVER/FISH.ASA", Codec::szdd},
    {"FISHBOWL.ASA", "SAVER/FISHBOWL.ASA", Codec::szdd}, {"FUTURE.ASA", "SAVER/FUTURE.ASA", Codec::szdd},
    {"HELL.ASA", "SAVER/HELL.ASA", Codec::plain},        {"ISLAND.ASA", "SAVER/ISLAND.ASA", Codec::szdd},
    {"OCEAN.ASA", "SAVER/OCEAN.ASA", Codec::szdd},       {"REPTILES.ASA", "SAVER/REPTILES.ASA", Codec::szdd},
    {"NERDCLOK.IMQ", "SAVER/NERDCLOK.IMQ", Codec::szdd}, {"PTERY.IMQ", "SAVER/PTERY.IMQ", Codec::szdd},
    {"ANTSW.DLL", "SAVER/ANTSW.DLL", Codec::szdd},       {"DIBDLL.DLL", "SAVER/DIBDLL.DLL", Codec::plain},
    {"INTRMLIB.DLL", "SAVER/INTRMLIB.DLL", Codec::szdd}, {"MEMMIDI.DLL", "SAVER/MEMMIDI.DLL", Codec::szdd},
    {"IMASAPLY.IMQ", "ENGINE/IMASAPLY.IMQ", Codec::plain}, {"INTERMIS.EXE", "ENGINE/INTERMIS.EXE", Codec::szdd},
};
// No resource holds a name: each ASA header's title and the IMQ modules'
// own strings, without their "FS-" prefix (Intermission's list of every
// installed product's modules needed it; the saver groups them by release).
const NameOverride kFarsideNames[] = {
    {"SAVER/AERIAL.ASA", "Aerial Grounds"},   {"SAVER/AMOEBA.ASA", "Amoeba"},
    {"SAVER/BIRDS.ASA", "Age of Mammals"},    {"SAVER/BISON.ASA", "Ballooning"},
    {"SAVER/EGGFIGHT.ASA", "Eggfight"},       {"SAVER/FISH.ASA", "Age of Fish"},
    {"SAVER/FISHBOWL.ASA", "Fishbowl"},       {"SAVER/FUTURE.ASA", "The Future"},
    {"SAVER/HELL.ASA", "Hell"},               {"SAVER/ISLAND.ASA", "Deserted Island"},
    {"SAVER/OCEAN.ASA", "Ocean"},             {"SAVER/REPTILES.ASA", "Age of Reptiles"},
    {"SAVER/NERDCLOK.IMQ", "Nerd Clock"},     {"SAVER/PTERY.IMQ", "Pterodactyl"},
};

// ---- dilbert -----------------------------------------------------------------------------
//
// Scott Adams' Dilbert Screen Saver Collection (Delrina, October 1994; under
// licence from United Feature Syndicate) on Intermission 5.0: 16 modules, 13
// ASA animations and three IMQ modules (DB-BEST, DB-CLOCK, DIL-WHAK), on four
// 1.44 MB floppies installed by Delrina's own Intermission Installer, as The
// Far Side's (research/win/pkg/dilbert, gitignored). Its ASA reader is The
// Far Side's byte for byte; its INTRMLIB, ANTSW and MEMMIDI are newer builds.

const char* const kDilbertModuleDirs[] = {"SAVER"};
// No image of the floppies exists online: the Internet Archive's flat ZIP
// of the four disks' files (item dilbert_screensaver_collection), and the
// same four disks as 1994 BBS copies, one ZIP per disk (DILBERT1..4.ZIP, the
// group's notes beside the files, never opened, inside item prog70_75):
// every file of the release is the same in both, byte for byte.
const KnownImage kDilbertImages[] = {
    {"ea6e18463d156fbb5c70401e39b45962", 4511167,
     "ZIP of the four install floppies' files (the Internet Archive's dilbert_screensaver_collection copy)", ""},
    {"1158cc6333d3b22dcd401a0593006e6f", 1077844,
     "ZIP of install disk 1's files (a 1994 BBS copy of the four floppies)", "", 1},
    {"4347386255e85cddb39a5d69ab65bc81", 1146156,
     "ZIP of install disk 2's files (a 1994 BBS copy of the four floppies)", "", 2},
    {"0f5408c77ed018db8b99b6b70f2a6a29", 1193935,
     "ZIP of install disk 3's files (a 1994 BBS copy of the four floppies)", "", 3},
    {"9064065cfb1edd12cc659823b5ca88ad", 1155239,
     "ZIP of install disk 4's files (a 1994 BBS copy of the four floppies)", "", 4},
};
// The flat ZIP first (the item that also holds the box photo); then the four
// ZIPs, each fetched from inside prog70_75's ZIP (no md5 published for a
// member: these are the members' own, measured 2026-09-30). Other bytes,
// other names.
const DownloadPart kDilbertDisks2to4[] = {
    {"https://archive.org/download/prog70_75/prog70_75.zip/prog70_75%2FPROG_70%2FDILBERT2.ZIP", L"DILBERT2.ZIP",
     1146156, "4347386255e85cddb39a5d69ab65bc81"},
    {"https://archive.org/download/prog70_75/prog70_75.zip/prog70_75%2FPROG_70%2FDILBERT3.ZIP", L"DILBERT3.ZIP",
     1193935, "0f5408c77ed018db8b99b6b70f2a6a29"},
    {"https://archive.org/download/prog70_75/prog70_75.zip/prog70_75%2FPROG_70%2FDILBERT4.ZIP", L"DILBERT4.ZIP",
     1155239, "9064065cfb1edd12cc659823b5ca88ad"},
};
const Download kDilbertDownloads[] = {
    {"https://archive.org/download/dilbert_screensaver_collection/DilbertS.zip", L"DilbertS.zip", 4511167,
     "ea6e18463d156fbb5c70401e39b45962", "zip"},
    {"https://archive.org/download/prog70_75/prog70_75.zip/prog70_75%2FPROG_70%2FDILBERT1.ZIP", L"DILBERT1.ZIP",
     1077844, "1158cc6333d3b22dcd401a0593006e6f", "zip", kDilbertDisks2to4},
};
// What the modules load (INTRMLIB -> ANTSW; DB-BEST and DB-CLOCK also DIBDLL,
// DB-BEST IM4_EXP; the ASA reader MEMMIDI, by name) and the ASA reader.
const char* const kDilbertRequired[] = {"SAVER/INTRMLIB.DLL", "SAVER/ANTSW.DLL",   "SAVER/DIBDLL.DLL",
                                        "SAVER/IM4_EXP.DLL",  "SAVER/MEMMIDI.DLL", "ENGINE/IMASAPLY.IMQ"};
// Every install disk's tag file (disk 1's, beside the installer and
// DB-CLOCK.IMQ, is the fingerprint's).
const char* const kDilbertDiskTags[] = {"DISK1", "DISK2", "DISK3", "DISK4"};
// IMINST2's install, flattened as The Far Side's. Never installed besides
// what The Far Side's never installs: ICONDLL.DLL (Intermission's own module
// icons; it probes WinG), ANTSW2.DLL (nothing imports it), MAPI.DLL and
// INTERMIS.LIB.
const LooseFile kDilbertLoose[] = {
    {"ATWORK.ASA", "SAVER/ATWORK.ASA", Codec::szdd},     {"CONOFHO.ASA", "SAVER/CONOFHO.ASA", Codec::szdd},
    {"CYBER.ASA", "SAVER/CYBER.ASA", Codec::szdd},       {"DRAW.ASA", "SAVER/DRAW.ASA", Codec::szdd},
    {"LAWYER.ASA", "SAVER/LAWYER.ASA", Codec::szdd},     {"LUNCH.ASA", "SAVER/LUNCH.ASA", Codec::szdd},
    {"OPTI.ASA", "SAVER/OPTI.ASA", Codec::szdd},         {"PRESENT.ASA", "SAVER/PRESENT.ASA", Codec::szdd},
    {"SHRED.ASA", "SAVER/SHRED.ASA", Codec::plain},      {"STDOGB.ASA", "SAVER/STDOGB.ASA", Codec::szdd},
    {"SWCROSS.ASA", "SAVER/SWCROSS.ASA", Codec::szdd},   {"THOR.ASA", "SAVER/THOR.ASA", Codec::szdd},
    {"WEDGIES.ASA", "SAVER/WEDGIES.ASA", Codec::szdd},   {"DB-BEST.IMQ", "SAVER/DB-BEST.IMQ", Codec::plain},
    {"DB-CLOCK.IMQ", "SAVER/DB-CLOCK.IMQ", Codec::plain}, {"DIL-WHAK.IMQ", "SAVER/DIL-WHAK.IMQ", Codec::szdd},
    {"ANTSW.DLL", "SAVER/ANTSW.DLL", Codec::szdd},       {"DIBDLL.DLL", "SAVER/DIBDLL.DLL", Codec::szdd},
    {"IM4_EXP.DLL", "SAVER/IM4_EXP.DLL", Codec::szdd},   {"INTRMLIB.DLL", "SAVER/INTRMLIB.DLL", Codec::szdd},
    {"MEMMIDI.DLL", "SAVER/MEMMIDI.DLL", Codec::szdd},   {"IMASAPLY.IMQ", "ENGINE/IMASAPLY.IMQ", Codec::plain},
    {"INTERMIS.EXE", "ENGINE/INTERMIS.EXE", Codec::szdd},
};
// No resource holds a name (each module's QUERY answers ""): the names the
// installer's own module list, PACKING.LST, gives them.
const NameOverride kDilbertNames[] = {
    {"SAVER/ATWORK.ASA", "Dilbert at Work"},
    {"SAVER/CONOFHO.ASA", "Conference Room of Horrors"},
    {"SAVER/CYBER.ASA", "Cyberspace"},
    {"SAVER/DRAW.ASA", "Artist Doodles"},
    {"SAVER/LAWYER.ASA", "Whack a Lawyer"},
    {"SAVER/LUNCH.ASA", "Out to Lunch"},
    {"SAVER/OPTI.ASA", "Happy Ratbert"},
    {"SAVER/PRESENT.ASA", "Dilbert Presents"},
    {"SAVER/SHRED.ASA", "Mad Shredder"},
    {"SAVER/STDOGB.ASA", "Saint Dogbert"},
    {"SAVER/SWCROSS.ASA", "Secretary with a Crossbow"},
    {"SAVER/THOR.ASA", "Thor Dog of Thunder"},
    {"SAVER/WEDGIES.ASA", "Bob Gives Wedgies"},
    {"SAVER/DB-BEST.IMQ", "Best of Dilbert"},
    {"SAVER/DB-CLOCK.IMQ", "Necktie Clock"},
    {"SAVER/DIL-WHAK.IMQ", "Budget Woes"},
};

// ---- box covers (COVERS.md §2.3) ------------------------------------------------------------
//
// Only URLs, md5s, sizes, paths and crops: the pictures are fetched (md5- and
// size-checked) or read from the disc being imported onto the user's machine,
// never shipped. The research behind each row is in
// research/win/pkg/covers/<id>/cover.json (gitignored).

using CK = CoverSource::Kind;

// A download source: an https URL as published, the md5 and size of the file.
constexpr CoverSource cover_download(const char* art, const char* label, const char* credit, const char* url,
                                     const char* md5, uint64_t size, const wchar_t* file_name, Crop crop = {}) {
  return CoverSource{CK::download, art, label, credit, url, md5, size, file_name, nullptr, nullptr, 0, 0, crop};
}
// A picture on the source being imported (resource 2 = an NE/PE RT_BITMAP).
constexpr CoverSource cover_disc(const char* art, const char* label, const char* credit, const char* path,
                                 const char* path_md5, Crop crop = {}, uint16_t resource_type = 0,
                                 uint16_t resource_id = 0) {
  return CoverSource{CK::disc, art, label, credit, nullptr, nullptr, 0, nullptr, path, path_md5, resource_type,
                     resource_id, crop};
}

// Deluxe: the box front from Berkeley Systems' own product page (1997, through
// the Wayback Machine; 162x195, and a tile is never shown larger than 160x200),
// else the setup wizard's portrait art on the disc, else the Internet
// Archive's scan of the disc label (the same item as the ISO).
const CoverSource kDeluxeCovers[] = {
    cover_download("box", "Box front", "Wayback Machine",
                   "https://web.archive.org/web/19970720113325id_/"
                   "http://www.berksys.com:80/products/afterdark/box.deluxe.gif",
                   "abb5ea84262cc6a2badea016f69cc7e8", 19460, L"berksys_box.deluxe.gif"),
    cover_disc("panel", "Setup art", "your disc", "ADE/PAGE1.BMP", kDeluxePage1Md5),
    cover_download("disc", "Disc label", "Internet Archive", "https://archive.org/download/after-dark-4-deluxe/disc.jpg",
                   "0b5104351ae6fa60da6d48164e8f548e", 737758, L"after-dark-4-deluxe_disc.jpg"),
};
// 10th Anniversary: the disc-label scan in the ISO's item, else the setup
// wizard's art (pages 1-6 are byte-identical). The box art the user owns has
// no downloadable copy: it becomes the cover only through --set-cover.
const CoverSource kAd10Covers[] = {
    cover_download("disc", "Disc label", "Internet Archive", "https://archive.org/download/ad10th/01_ad10_cd.jpg",
                   "e1e77b74ccc9bcd4e5b818f841f0614d", 376876, L"ad10th_01_ad10_cd.jpg"),
    cover_disc("panel", "Setup art", "your disc", "ADE/PAGE1.BMP", "30f247d08fe8a4fd394658a3c4564a06"),
};
// 3.2: no box scan of 3.0 or 3.2 exists; the installer splash comes first,
// cropped above its warning and copyright rows, then two scans of the label.
const CoverSource kAd32Covers[] = {
    cover_disc("splash", "Installer art", "your disc", "INSTALL/SETUP.BMP", "67e76581f69bcfdb62ef1c7ff61fc426",
               Crop{0, 0, 387, 183}),
    cover_download("disc", "Disc label", "Internet Archive", "https://archive.org/download/after-dark-v3_2/disc.jpg",
                   "68f2aad89dcdc1fdbcb3419ab42077f9", 349982, L"after-dark-v3_2_disc.jpg"),
    cover_download("disc", "Disc label", "Internet Archive",
                   "https://archive.org/download/berkeley-systems-after-dark-for-windows/"
                   "berkeley-systems-after-dark-for-windows.png",
                   "f2fdf32138f96da06f8d348af059d712", 1857714, L"berkeley-systems-after-dark-for-windows.png"),
};
// Totally Twisted: the box front from Berkeley Systems' product page (1997,
// through the Wayback Machine; 127x162, the retail box's art), else the box
// front of Sierra's later edition from The Sierra Chest (through the Wayback
// Machine; 498x599), else the installer splash, cropped above its warning
// text, else the TTW320CD item's TIFF scan of the disc (2840x2888).
const CoverSource kTtCovers[] = {
    cover_download("box", "Box front", "Wayback Machine",
                   "https://web.archive.org/web/19970720113451id_/"
                   "http://www.berksys.com:80/products/afterdark/box.twistedL.jpg",
                   "5aa9478d761a580f1d9006ee41d0cd3f", 26382, L"berksys_box.twistedL.jpg"),
    cover_download("box", "Box front", "Wayback Machine",
                   "https://web.archive.org/web/20230422055429id_/"
                   "https://www.sierrachest.com/gfx/games/AfterDarkTotallyTwisted/box/01_front.JPG",
                   "3f87e84e3d86d7a2d6f96c86a8102452", 53679, L"sierrachest_AfterDarkTotallyTwisted_01_front.jpg"),
    cover_disc("splash", "Installer art", "your disc", "INSTALL/SETUP.BMP", kTtSetupBmpMd5, Crop{0, 0, 387, 204}),
    cover_download("disc", "Disc label", "Internet Archive", "https://archive.org/download/TTW320CD/TTW320CD.tif",
                   "ec19d74fd2ac46d4bc8f6021ad0011e6", 24632572, L"TTW320CD.tif"),
};
// The Simpsons: the box front (Fox's art: fetched onto the user's machine
// only, never bundled), from Wikisimpsons, else the Wayback Machine's copy of
// the full-box scan it was cut from; else the installer splash in SETUP.EXE.
const CoverSource kSimpsonsCovers[] = {
    cover_download("box", "Box front", "Wikisimpsons",
                   "https://static.simpsonswiki.com/images/7/72/The_Simpsons_Screen_Saver.png",
                   "47f4619da9e79b126a4fb45770f0e649", 1011608, L"The_Simpsons_Screen_Saver.png"),
    cover_download("box", "Box front", "Wayback Machine",
                   "https://web.archive.org/web/20250715075938id_/"
                   "https://www.whipassgaming.com/images/deadsections/mac/simpsonsfullbox.jpg",
                   "94db22db1e89b3ff2fdb97e610056602", 484234, L"simpsonsfullbox.jpg", Crop{0, 0, 600, 776}),
    cover_disc("splash", "Installer art", "your disks", "SETUP.EXE", "980867b7ab5394b09adad725d375ba95",
               Crop{0, 0, 387, 172}, 2, 7500),
};

// Star Wars Screen Entertainment: the box front from Presage's own product
// page (1997, through the Wayback Machine; 150x200), else Wookieepedia's photo
// of the same US box (the Wayback Machine's byte-exact capture of the stored
// original: Fandom's live URL rewrites what it serves), else two archive.org
// scans of the disc label, the second cropped to the disc. LucasArts' art:
// fetched onto the user's machine only, never bundled. The disc itself has no
// picture a disc source can reach (every one is inside the ARJ archives).
const CoverSource kSwseCovers[] = {
    cover_download("box", "Box front", "Wayback Machine",
                   "https://web.archive.org/web/19970310054846id_/"
                   "http://www.presage.com:80/images/pimages/box-starwars.JPEG",
                   "8b84792a21f3a21e09cc2809d263d9c1", 30600, L"presage_box-starwars.jpg"),
    cover_download("box", "Box front", "Wayback Machine",
                   "https://web.archive.org/web/20221205171117id_/"
                   "https://static.wikia.nocookie.net/starwars/images/9/9a/SWScreenEntertainment.jpg/revision/latest",
                   "dc4e541d1a79a46747caf0cb6f425c0a", 190239, L"wookieepedia_SWScreenEntertainment.jpg"),
    cover_download("disc", "Disc label", "Internet Archive", "https://archive.org/download/swse1/1.jpg",
                   "a40d11a61ee0288048bdfdd28e48e57c", 2156659, L"swse1_1.jpg"),
    cover_download("disc", "Disc label", "Internet Archive",
                   "https://archive.org/download/cd_AfterDark_Star_Wars_ScreenSaver_for_Win3.1/"
                   "AfterDark%20Star%20Wars%20-%20CD.jpg",
                   "b8ac25eb20a87f44e47ff8ed097698d7", 948614, L"cd_AfterDark_Star_Wars_ScreenSaver_for_Win3.1_CD.jpg",
                   Crop{20, 14, 1424, 1424}),
};

// Star Trek: The Screen Saver: the Windows retail box front from the
// Internet Archive's box scans (item afterdark-20b_startrek_box, 1180x1525:
// it fills the tile), else the same front at 600 dpi, else the scan of disk
// 1's label in the disk images' own item (drawn as a picture, never cut to a
// disc: it is a floppy's). Paramount's and Berkeley's art: fetched onto the
// user's machine only, never bundled. The disks have no picture a disc source
// can reach (every one is KWAJ-compressed).
const CoverSource kStartrekCovers[] = {
    cover_download("box", "Box front", "Internet Archive",
                   "https://archive.org/download/afterdark-20b_startrek_box/Aaa_itemimage.jpg",
                   "157eb04fcc9bdc0d4a831148ca6cc260", 577239, L"afterdark-20b_startrek_box_Aaa_itemimage.jpg"),
    cover_download("box", "Box front", "Internet Archive",
                   "https://archive.org/download/afterdark-20b_startrek_box/"
                   "After%20Dark%202.0b%20-%20Star%20Trek%20-%20Box%20-%20Front.jpg",
                   "f41d1dbdaadaeeb0f9bc0a6aa76754ce", 9277274, L"After Dark 2.0b - Star Trek - Box - Front.jpg"),
    cover_download("panel", "Disk label", "Internet Archive",
                   "https://archive.org/download/afterdark-20b_startrek/afterdark-20b_startrek_disk1.jpg",
                   "dbda3bc66b809f446a17138073579b53", 569964, L"afterdark-20b_startrek_disk1.jpg"),
};

// Marvel Comics Screen Posters: the Internet Archive's photo of the Windows
// box front (the item of the flat ZIP; 1200x1505, cropped to the box: the
// camera's date stamp inside it stays), else the 1993 magazine advertisement
// showing the same box, drawn as a picture. Marvel's and Berkeley's art:
// fetched onto the user's machine only, never bundled. The disks have no
// picture a disc source can reach (every one is inside the libraries).
const CoverSource kMarvelCovers[] = {
    cover_download("box", "Box front", "Internet Archive",
                   "https://archive.org/download/afterdarkmarvelscreenposters/box.jpg",
                   "1b9294c6bd03c5b14ed366cc652c8e7c", 903667, L"afterdarkmarvelscreenposters_box.jpg",
                   Crop{28, 64, 1132, 1390}),
    cover_download("panel", "Advertisement", "Internet Archive",
                   "https://archive.org/download/marval-computer/MarvalComputer.jpg",
                   "f2644bb771fd8cbba1c88e77937b5572", 3229147, L"marval-computer_MarvalComputer.jpg"),
};
// Snoopy's Screen Savers: no box, label or manual scan of the Windows release
// exists online; the picture its installer shows beside the readme on disk 1
// (AD_MODS.BMP, Image Smith's logo, 79x175), drawn as a picture.
const CoverSource kSnoopyCovers[] = {
    cover_disc("panel", "Setup art", "your disks", "AD_MODS.BMP", "9befcefa9fafbb5e7c36ccfe325c607d"),
};

// The Looney Tunes Screen Saver: the box front from Berkeley Systems' product
// page (1997, through the Wayback Machine; 127x162, as Totally Twisted's),
// else the installer splash, cropped above its warning text, else the scan
// of the CD label (of the August CD of the same release). Warner Bros.' and
// Berkeley's art: fetched onto the user's machine only, never bundled.
const CoverSource kLooneyCovers[] = {
    cover_download("box", "Box front", "Wayback Machine",
                   "https://web.archive.org/web/19970720113529id_/"
                   "http://www.berksys.com:80/products/afterdark/box.looneytunesL.jpg",
                   "e9fa28ed00032bb04a436132a724e98c", 29771, L"berksys_box.looneytunesL.jpg"),
    cover_disc("splash", "Installer art", "your disks", "SETUP.BMP", "32af5fcb5add7fc88de7b03b5c531563",
               Crop{0, 0, 387, 161}),
    cover_download("disc", "Disc label", "Internet Archive",
                   "https://archive.org/download/berkeley_systems_looney_tunes/16_looney_tunes_CD.jpg",
                   "8b168e0679d2661889092fc6280d509a", 369574, L"berkeley_systems_looney_tunes_16_looney_tunes_CD.jpg"),
};
// ScreamSavers: no box or label scan exists online; the installer's title
// art in SETUP.EXE (bitmap 7500, 350x179), cropped above its copyright block.
const CoverSource kScreamsCovers[] = {
    cover_disc("splash", "Installer art", "your disks", "SETUP.EXE", "e348fb48b89102903a3b26a3c8aedab3",
               Crop{0, 0, 350, 119}, 2, 7500),
};
// The Disney Collection Screen Saver: the box front from Berkeley Systems'
// product page (1997, through the Wayback Machine; 128x162), else the
// installer splash, cropped above its warning text. Disney's and Berkeley's
// art: fetched onto the user's machine only, never bundled.
const CoverSource kDisneyCovers[] = {
    cover_download("box", "Box front", "Wayback Machine",
                   "https://web.archive.org/web/19970720111656id_/"
                   "http://www.berksys.com:80/lite/products/afterdark/box.disneyL.jpg",
                   "ffcd41dd737b125af0a4e4a1bfee6610", 20983, L"berksys_box.disneyL.jpg"),
    cover_disc("splash", "Installer art", "your disks", "SETUP.BMP", "39e1bfb21fdf7fe2396525d13798cf50",
               Crop{0, 0, 387, 172}),
};
// The Far Side Screen Saver Collection: the photo in the floppy images' item
// of two boxes on a couch (1080x813 WebP), cropped to the release's. Gary
// Larson's and Delrina's art: fetched onto the user's machine only, never
// bundled. (WIC decodes WebP where its codec is installed; else the tile is
// drawn.) The disks' only picture, the installer's INSTALL.BMP, is
// SZDD-compressed, out of a disc source's reach.
const CoverSource kFarsideCovers[] = {
    cover_download("box", "Box front", "Internet Archive",
                   "https://archive.org/download/the-far-side-screen-saver-collection-1-of-5/"
                   "far-side-software-v0-z46qj0d0a2fc1.webp",
                   "4e7ebc4e9dbced47a3fc37e55054486f", 270222, L"the-far-side-screen-saver-collection_box.webp",
                   Crop{546, 122, 408, 508}),
};
// Scott Adams' Dilbert Screen Saver Collection: the Internet Archive's photo
// of the box front (the flat ZIP's item; 1200x1600, cropped to the box: the
// previous owner's name written on it stays), else the installer's picture
// beside its pages on disk 1 (INSTALL.BMP, Dogbert, 63x123), drawn as a
// picture. Scott Adams' and Delrina's art: fetched or read onto the user's
// machine only, never bundled.
const CoverSource kDilbertCovers[] = {
    cover_download("box", "Box front", "Internet Archive",
                   "https://archive.org/download/dilbert_screensaver_collection/box.jpg",
                   "aa8fe2600200685504ea9f15feaf4352", 167593, L"dilbert_screensaver_collection_box.jpg",
                   Crop{100, 215, 965, 1315}),
    cover_disc("panel", "Setup art", "your disks", "INSTALL.BMP", "47199572d43fb457b952dcba197a19c5"),
};

const Package kPackages[] = {
    {"deluxe", "After Dark 4.0 Deluxe", "Deluxe", Recipe::tree, "FILES", kDeluxeModuleDirs, kDeluxeImages,
     kDeluxeRequired, kDeluxeCopy, nullptr, {}, nullptr, nullptr, nullptr, {}, {}, {}, manifest(kDeluxeKnown),
     kDeluxeDownloads, kDeluxeCovers, "1996-10"},  // disc mastered 1996-10-12; modules dated 1996-09
    {"ad10", "After Dark 10th Anniversary", "10th Anniversary", Recipe::tree, "packages/ad10", kAd10ModuleDirs,
     kAd10Images, kAd10Required, kAd10Copy, "AD10TH/ADXPL40.DLL", kAd10Absent, nullptr, nullptr, nullptr, {},
     kAd10Fixups, kAd10Names, manifest(kAd10Known), kAd10Downloads, kAd10Covers, "1999-09"},  // disc mastered 1999-09-06
    {"ad32", "After Dark 3.2", "After Dark 3.2", Recipe::ad3zip, "packages/ad32", kAd32ModuleDirs, kAd32Images,
     kAd32Required, {}, kAd32Marker, {}, "AD32", "ADXPL300.DLL", "AD3.AFI", {}, {}, {}, manifest(kAd32Known),
     kAd32Downloads, kAd32Covers, "1995-08-02"},  // newest file on the disc (its PVD date is a bogus 1993)
    {"tt", "Totally Twisted After Dark", "Totally Twisted", Recipe::ad3zip, "packages/tt", kTtModuleDirs, kTtImages,
     kTtRequired, {}, nullptr, {}, "TWISTED", "ADXPL40.DLL", "PHLEM.AFI", {}, {}, {}, manifest(kTtKnown),
     kTtDownloads, kTtCovers, "1995-08-08"},  // newest file on the disc, days after 3.2 (PVD date bogus too)
    {"simpsons", "The Simpsons Screen Saver", "Simpsons", Recipe::ad3zip, "packages/simpsons", kSimpsonsModuleDirs,
     kSimpsonsImages, kSimpsonsRequired, {}, nullptr, {}, "SIMPSONS", "ADXPL310.DLL", "SAX.AFI", kSimpsonsArchives,
     {}, {}, manifest(kSimpsonsKnown), kSimpsonsDownloads, kSimpsonsCovers, "1994-08"},  // modules dated 1994-08-02
    // Every Windows build found dates from 1994-08-20 at the earliest
    // (INTERMIS.EXE); LucasArts announced July 1994 for both platforms. This
    // CD is a later build (files 1994-10), mastered 1995-05-24. It sorts after
    // the Simpsons (1994-08) by registry order on the tie.
    {"swse", "Star Wars Screen Entertainment", "Star Wars", Recipe::intermission, "packages/swse", kSwseModuleDirs,
     kSwseImages, kSwseRequired, {}, nullptr, {}, "SAVER", nullptr, nullptr, kSwseArchives, {}, kSwseNames,
     manifest(kSwseKnown), kSwseDownloads, kSwseCovers, "1994-08", "SWSE", kSwseLoose},
    // The newest files on the disks are dated 1992-11-16 (the modules). After
    // the first six in the registry, so they keep their places (the GUI's
    // per-release command ids go by registry index); first in the catalog's
    // packages list.
    // Some of its modules compose a fixed 640x480 scene (at larger screens
    // The Mission sits top-left with a band; Final Exam and Sickbay sit small
    // in the middle), and the others lay out for whatever screen they get:
    // the catalog gives all 16 that screen, so the release looks as it did at
    // 640x480.
    {"startrek", "Star Trek: The Screen Saver", "Star Trek", Recipe::ad2kwaj, "packages/startrek",
     kStartrekModuleDirs, kStartrekImages, kStartrekRequired, {}, nullptr, {}, "AFTERDRK", nullptr, nullptr,
     kStartrekDiskTags, {}, kStartrekNames, manifest(kStartrekKnown), kStartrekDownloads, kStartrekCovers, "1992-11",
     nullptr, kStartrekLoose, "Star Trek\xAE: The Screen Saver", "640x480", Package::About::ad20},
    // The releases added after Star Trek: The Screen Saver follow it, so the
    // first seven keep their places (and the GUI's command ids).
    // The libraries and MARVEL.AD are dated 1993-12-13 (its readme, December
    // 15, 1993). Each poster is a fixed 640x480 picture, drawn in the middle
    // of a larger screen with its caption at the bottom of the whole screen:
    // the catalog gives it that screen, as for Star Trek: The Screen Saver.
    {"marvel", "Marvel Comics Screen Posters", "Marvel", Recipe::islib, "packages/marvel", kMarvelModuleDirs,
     kMarvelImages, kMarvelRequired, {}, nullptr, {}, "AFTERDRK", nullptr, nullptr, kMarvelLibraries, {}, {},
     manifest(kMarvelKnown), kMarvelDownloads, kMarvelCovers, "1993-12", nullptr, {}, nullptr, "640x480",
     Package::About::as_is, {}, "modules.lib", "MARVEL.AD", kMarvelTable},
    // The library is dated 1994-10-19, the newest modules 1994-10-13. The
    // modules lay out for any screen.
    {"snoopy", "Snoopy's Screen Savers", "Snoopy", Recipe::islib, "packages/snoopy", kSnoopyModuleDirs, kSnoopyImages,
     {}, {}, nullptr, {}, "AFTERDRK", nullptr, nullptr, kSnoopyLibraries, {}, {}, manifest(kSnoopyKnown),
     kSnoopyDownloads, kSnoopyCovers, "1994-10", nullptr, {}, nullptr, nullptr, Package::About::as_is, {}, "AD_MODS.z",
     "IS_FLY.AD", kSnoopyTable},
    // Every file of the April build is dated 1995-04-11/12; Berkeley
    // announced it on 1995-04-25. It ties with ScreamSavers and comes first.
    {"looney", "The Looney Tunes Screen Saver", "Looney Tunes", Recipe::ad3zip, "packages/looney", kLooneyModuleDirs,
     kLooneyImages, kLooneyRequired, {}, nullptr, {}, "LNYTUNES", "ADXPL41.DLL", "LNYTUNES.AFI", kLooneyArchives, {},
     {}, manifest(kLooneyKnown), kLooneyDownloads, kLooneyCovers, "1995-04"},
    // The newest file on the disks is ENGINE.ZIP, 1995-04-11 (its SETUP.PKG
    // lists an earlier one: disk 1 was remastered with the 3.0.6 engine).
    // Four modules paint a 640x480 scene and one composes one 640 wide, drawn
    // small in the middle of a larger screen: the catalog gives all 15 that
    // screen, as for Star Trek: The Screen Saver.
    {"screams", "ScreamSavers", "ScreamSavers", Recipe::ad3zip, "packages/screams", kScreamsModuleDirs,
     kScreamsImages, kScreamsRequired, {}, nullptr, {}, "SCREAMS", "ADXPL300.DLL", "SCREAMS.AFI", kScreamsArchives, {},
     {}, manifest(kScreamsKnown), kScreamsDownloads, kScreamsCovers, "1995-04", nullptr, {}, nullptr, "640x480"},
    // The newest files (the script, the package list, AFI.ZIP) are dated
    // 1995-09-13.
    {"disney", "The Disney Collection Screen Saver", "Disney", Recipe::ad3zip, "packages/disney", kDisneyModuleDirs,
     kDisneyImages, kDisneyRequired, {}, nullptr, {}, "DISNEY", "ADXPL100.DLL", "DISNEY.AFI", kDisneyArchives, {},
     kDisneyNames, manifest(kDisneyKnown), kDisneyDownloads, kDisneyCovers, "1995-09", nullptr, {}, nullptr, nullptr,
     Package::About::as_is, kDisneyNeverOpened},
    // The two Delrina Intermission releases follow, so the first twelve keep
    // their places (and the GUI's command ids). Every file of The Far Side's
    // disks is dated 1994-06-19 (the BBS copy, 1994-06-30); Dilbert's
    // 1994-10-06. Intermission's modules are shown at 640x480 by their ABI,
    // as Star Wars Screen Entertainment's are: no screen of their own.
    {"farside", "The Far Side Screen Saver Collection", "Far Side", Recipe::intermission, "packages/farside",
     kFarsideModuleDirs, kFarsideImages, kFarsideRequired, {}, "PTERY.IMQ", {}, "SAVER", nullptr, nullptr,
     kFarsideDiskTags, {}, kFarsideNames, manifest(kFarsideKnown), kFarsideDownloads, kFarsideCovers, "1994-06",
     nullptr, kFarsideLoose},
    {"dilbert", "Scott Adams' Dilbert Screen Saver Collection", "Dilbert", Recipe::intermission, "packages/dilbert",
     kDilbertModuleDirs, kDilbertImages, kDilbertRequired, {}, "DB-CLOCK.IMQ", {}, "SAVER", nullptr, nullptr,
     kDilbertDiskTags, {}, kDilbertNames, manifest(kDilbertKnown), kDilbertDownloads, kDilbertCovers, "1994-10",
     nullptr, kDilbertLoose},
};

}  // namespace

bool Package::is_deluxe() const { return std::string_view(root) == "FILES"; }

bool Package::delrina_installer() const { return recipe == Recipe::intermission && !install_name; }

const char* recipe_name(Recipe r) {
  switch (r) {
    case Recipe::tree: return "tree";
    case Recipe::ad3zip: return "ad3zip";
    case Recipe::intermission: return "intermission";
    case Recipe::ad2kwaj: return "ad2kwaj";
    case Recipe::islib: return "islib";
  }
  return "?";
}

uint64_t download_size(const Download& d) {
  uint64_t n = d.size;
  for (const DownloadPart& p : d.more_images) n += p.size;
  return n;
}

std::span<const Package> builtin_packages() { return kPackages; }

std::span<const Package> registry_or_builtin(std::span<const Package> registry) {
  return registry.empty() ? builtin_packages() : registry;
}

const Package* find_package(std::string_view id, std::span<const Package> registry) {
  for (const Package& p : registry_or_builtin(registry))
    if (id == p.id) return &p;
  return nullptr;
}

std::string known_releases(std::span<const Package> registry) {
  std::string s;
  for (const Package& p : registry_or_builtin(registry)) {
    if (!s.empty()) s += ", ";
    s += p.title;
  }
  return s;
}

std::vector<std::string> downloadable_packages(std::span<const Package> registry) {
  std::vector<std::string> ids;
  for (const Package& p : registry_or_builtin(registry))
    if (!p.downloads.empty()) ids.push_back(p.id);
  return ids;
}

}  // namespace adw::import
